-- MySQL Script generated by MySQL Workbench
-- Thu Nov  1 00:26:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL,
  `password` VARCHAR(300) NULL,
  `name` VARCHAR(200) NULL,
  `email` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Feed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Feed` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `feed` TEXT NULL,
  `date` DATETIME NULL,
  `fk_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Feed_User_idx` (`fk_user` ASC),
  CONSTRAINT `fk_Feed_User`
    FOREIGN KEY (`fk_user`)
    REFERENCES `User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
